---
#info: Open the IPMI webinterface in Chromium on your local machine and try to autologin
- name: Autologin to IPMI URL
  connection: local
  shell: supermicro-auto-browse {{ im_ipmi_host }} {{ im_ipmi_user }} {{ im_ipmi_password }} || chromium {{ im_ipmi_host }} &
  become: false
