---
#info: Get the MAC address of LAN1 (Supermicro)
- include_role: name=servermonkey.ipmi_runner
  vars:
    ipmi_log: get-mac-lan1
    ipmi_command: raw 0x30 0x21 | tail -c 18 | sed 's/ /:/g'
#todo
# first check if this is a supermicro board with: mc info