---
#info: Open a remote VNC-like terminal via Supermicro ikvm, with browser fallback
- block:
    - name: Open ikvm terminal
      connection: local
      shell: ikvm {{ im_ipmi_host }} {{ im_ipmi_user }} {{ im_ipmi_password }}
      become: false

  rescue:
    - name: Fallback to browser
      include_role: name=servermonkey.ipmi
      vars:
        task: browse
