---
#info: Set the UID LED to off (Supermicro)
- include_role: name=servermonkey.ipmi_runner
  vars:
    ipmi_log: led-off
    ipmi_command: raw 0x30 0x0e
#todo
# first check if this is a supermicro board with: mc info