---
#info: Request system turn on, but wait a second between each host
- name: Power on
  connection: local
  ipmi_power:
    name: '{{ ipmi_host }}'
    user: '{{ ipmi_user }}'
    password: '{{ ipmi_password }}'
    state: 'on'
  register: shell
  async: 60
  poll: 3
  throttle: 1
  become: false

- name: Check on an async task
  connection: local
  async_status:
    jid: "{{ shell.ansible_job_id }}"
  register: job
  until: job.finished
  retries: 1000
  delay: 3
  become: false

- debug:
    var: job.stdout_lines
  when: job.stdout_lines is defined