---
#info: Request system reset (reboot) without waiting for the OS
- name: Reset
  connection: local
  ipmi_power:
    name: '{{ ipmi_host }}'
    user: '{{ ipmi_user }}'
    password: '{{ ipmi_password }}'
    state: 'reset'
  register: shell
  async: 60
  poll: 0
  throttle: 20
  become: false

- name: Check on an async task
  connection: local
  async_status:
    jid: "{{ shell.ansible_job_id }}"
  register: job
  until: job.finished
  retries: 1000
  delay: 3
  become: false

- debug:
    var: job.stdout_lines
  when: job.stdout_lines is defined
